name: Run Automation Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Configurar Java 17 y Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN

      - name: Ejecutar pruebas
        run: mvn --batch-mode -U test -Dautomation.headless=true
        env:
          MAVEN_USERNAME: Ozra022
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

      - name: Subir evidencias
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-evidence
          path: test-evidence/
          if-no-files-found: warn